name: Cookiecutter Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cookiecutter:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Cookiecutter
      run: pip install cookiecutter

    - name: Create context file
      run: |
        echo '{ "module": "go-project" }' > cc-context.json

    - name: Build project
      run: |
        cookiecutter . --no-input --config-file cc-context.json
      
    - name: Debug
      run: |
        pwd
        ls -la
        ls -la go-project

    - name: Generate artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: go-project
        path: ./go-project
        retention-days: 1
