name: Cookiecutter Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cookiecutter:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Cookiecutter
      run: pip install cookiecutter

    - name: Create context file
      run: |
        echo 'default_context:
          module: gha-test
        ' > cc-context.yaml

    - name: Build project
      run: |
        cookiecutter . --no-input --config-file cc-context.yaml
      
    - name: Generate artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: gha-test
        path: ./gha-test
        retention-days: 1
